### ISSUE TITLE
[FEAT] Select View Collection View Cell 세팅

### ISSUE THREAD

**Issue by hellozo0** [WESOPT29th-Hackathon-Team6/MEEW-Client#3]
## 📌  Feature Issue
 Select View Collection View Cell 세팅

## 📝  To-do
- [ ] Collection View관련 extension 연결
- [x] Collection VIew 관련 데이터 연결
- [x] Collection View xib 생성
- [x] Xib 레이아웃 짜기
