### ISSUE TITLE
[REFACTOR] Archive, Setting, ProfileEdit View 코드 정리

### ISSUE THREAD

**Issue by Taehyeon-Kim** [WESOPT29th-Hackathon-Team6/MEEW-Client#54]
## 📌  Feature Issue

Archive, Setting, ProfileEdit View 코드 정리

## 📝  To-do

- [x] Archive View 코드 정리 (+ UI)
- [ ] Setting View 코드 정리 (+ UI)
- [ ] ProfileEdit View 코드 정리 (+ UI)
